"""making mobile default

Revision ID: 045109d52f65
Revises: dd9f177b865a
Create Date: 2023-10-16 19:44:41.366842

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "045109d52f65"
down_revision = "dd9f177b865a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
