"""adding user id to the services

Revision ID: 1df0737d6960
Revises: 6c8d1d2a4d83
Create Date: 2023-12-09 13:17:51.583142

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1df0737d6960"
down_revision = "6c8d1d2a4d83"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_services", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user_services", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_services", type_="foreignkey")
    op.drop_column("user_services", "user_id")
    # ### end Alembic commands ###
