"""correction

Revision ID: 2202a2def64f
Revises: cc544c092464
Create Date: 2023-09-09 23:13:43.641168

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2202a2def64f"
down_revision = "cc544c092464"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
