"""education_new_columns

Revision ID: 24ccb9016248
Revises: 9af0577cfc9c
Create Date: 2023-09-10 01:01:56.362063

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "24ccb9016248"
down_revision = "9af0577cfc9c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "education", sa.Column("mode_of_study", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "education", sa.Column("degree_type", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "education", sa.Column("area_of_study", sa.String(length=200), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("education", "area_of_study")
    op.drop_column("education", "degree_type")
    op.drop_column("education", "mode_of_study")
    # ### end Alembic commands ###
