"""adding order and show on profile tag to the repositories model

Revision ID: 3c5062aca24d
Revises: 3e5c4d2b3251
Create Date: 2024-05-06 00:38:10.178183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5062aca24d'
down_revision = '3e5c4d2b3251'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('show_on_profile', sa.Boolean(), nullable=False))
    op.add_column('repositories', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'order')
    op.drop_column('repositories', 'show_on_profile')
    # ### end Alembic commands ###
