"""repositories table

Revision ID: 3e5c4d2b3251
Revises: a0c9260c5dcf
Create Date: 2024-05-06 00:12:21.236953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5c4d2b3251'
down_revision = 'a0c9260c5dcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('repo_name', sa.String(length=150), nullable=False),
    sa.Column('repo_description', sa.Text(), nullable=True),
    sa.Column('repo_url', sa.String(length=150), nullable=False),
    sa.Column('repo_language', sa.String(length=150), nullable=False),
    sa.Column('repo_created_at', sa.DateTime(), nullable=False),
    sa.Column('repo_updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repositories')
    # ### end Alembic commands ###
