"""upgrade to relationships revert

Revision ID: 3ef5ebf3732e
Revises: 983317122ead
Create Date: 2023-10-21 13:57:34.777793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef5ebf3732e'
down_revision = '983317122ead'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
