"""updating user model for skills again

Revision ID: 472b7df179a1
Revises: d39239304412
Create Date: 2023-11-18 20:32:12.501243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472b7df179a1'
down_revision = 'd39239304412'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
