"""projects

Revision ID: 474d7259ab7d
Revises: d74db4255e02
Create Date: 2024-01-27 16:31:08.118423

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "474d7259ab7d"
down_revision = "d74db4255e02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_projects",
        sa.Column("project_name", sa.String(length=200), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("from_date", sa.DateTime(), nullable=True),
        sa.Column("to_date", sa.DateTime(), nullable=True),
        sa.Column("project_link", sa.String(length=200), nullable=True),
        sa.Column("technologies", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_projects")
    # ### end Alembic commands ###
