"""overlaps

Revision ID: 55184c4301c5
Revises: 1df0737d6960
Create Date: 2023-12-09 16:39:18.124872

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "55184c4301c5"
down_revision = "1df0737d6960"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
