"""mking a unique foreign key for user skill association

Revision ID: 63950dd689b5
Revises: b97c3ef125e7
Create Date: 2023-10-18 00:16:45.709476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63950dd689b5'
down_revision = 'b97c3ef125e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_skill_association', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'user_skill_association', ['skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_skill_association', type_='unique')
    op.alter_column('user_skill_association', 'skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
