"""user services

Revision ID: 6c8d1d2a4d83
Revises: 5243c4e893fe
Create Date: 2023-11-24 19:20:00.637529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8d1d2a4d83'
down_revision = '5243c4e893fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_services',
    sa.Column('service_name', sa.String(length=200), nullable=True),
    sa.Column('service_description', sa.String(length=200), nullable=True),
    sa.Column('service_icon', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_services')
    # ### end Alembic commands ###
