"""adding order and show on profile tag to the repositories model 2\2

Revision ID: 77ca191bbb11
Revises: a241ab4bacf8
Create Date: 2024-05-06 23:40:10.505694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ca191bbb11'
down_revision = 'a241ab4bacf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'repo_language',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('repositories', 'repo_language',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    # ### end Alembic commands ###
