"""skill_mapping_change

Revision ID: 7b6b238a6431
Revises: 63950dd689b5
Create Date: 2023-10-19 01:50:21.505540

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7b6b238a6431"
down_revision = "63950dd689b5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
