"""correction_ex

Revision ID: 7f31e8dc478c
Revises: 2202a2def64f
Create Date: 2023-09-09 23:15:02.634227

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "7f31e8dc478c"
down_revision = "2202a2def64f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
