"""reverting_skill_mapping

Revision ID: 8e4130f1af80
Revises: 7b6b238a6431
Create Date: 2023-10-19 01:57:48.064286

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8e4130f1af80"
down_revision = "7b6b238a6431"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
