"""upgrade to relationships

Revision ID: 983317122ead
Revises: 8e4130f1af80
Create Date: 2023-10-21 13:35:23.155243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983317122ead'
down_revision = '8e4130f1af80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
