"""new coloumn for education

Revision ID: 9a33506b94f1
Revises: 24ccb9016248
Create Date: 2023-09-10 01:39:24.109999

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9a33506b94f1"
down_revision = "24ccb9016248"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "education", sa.Column("currenty_studying", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("education", "currenty_studying")
    # ### end Alembic commands ###
