"""correction_exe

Revision ID: 9af0577cfc9c
Revises: 7f31e8dc478c
Create Date: 2023-09-09 23:15:47.417538

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9af0577cfc9c"
down_revision = "7f31e8dc478c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
