"""adding order and show on profile tag to the repositories model 122

Revision ID: a241ab4bacf8
Revises: 3c5062aca24d
Create Date: 2024-05-06 20:02:58.561646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a241ab4bacf8'
down_revision = '3c5062aca24d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
