"""upgrade to relationships revert again

Revision ID: a6f29f904180
Revises: 3ef5ebf3732e
Create Date: 2023-10-21 13:58:30.400191

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a6f29f904180"
down_revision = "3ef5ebf3732e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
