"""some alterations3

Revision ID: c7ce8984ad07
Revises: 4e4ee630e8e3
Create Date: 2023-10-27 00:00:25.660107

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c7ce8984ad07"
down_revision = "4e4ee630e8e3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
