"""proj2

Revision ID: ca4e49c155b9
Revises: 474d7259ab7d
Create Date: 2024-02-10 15:03:30.303779

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ca4e49c155b9"
down_revision = "474d7259ab7d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
