"""updating user model for skills

Revision ID: d39239304412
Revises: f3e6d9345c7d
Create Date: 2023-11-18 20:30:11.706425

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d39239304412"
down_revision = "f3e6d9345c7d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
