"""test

Revision ID: d74db4255e02
Revises: 55184c4301c5
Create Date: 2023-12-09 16:41:52.695552

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d74db4255e02"
down_revision = "55184c4301c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
