"""making skill and percentages

Revision ID: dd9f177b865a
Revises: 96040fb19280
Create Date: 2023-10-06 00:25:27.761585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd9f177b865a'
down_revision = '96040fb19280'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'percentage')
    op.alter_column('user', 'mobile_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_skill_association', sa.Column('percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skill_association', 'percentage')
    op.alter_column('user', 'mobile_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('skill', sa.Column('percentage', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
