"""remioving mobile number

Revision ID: f3e6d9345c7d
Revises: 849379c8a023
Create Date: 2023-11-18 19:07:33.801844

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f3e6d9345c7d"
down_revision = "849379c8a023"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "mobile_number", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "mobile_number", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
